sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: HC37wsUGdKSUfVItj7YzWWL5iDSODsctm2X4PT63H5UWJ45QqMsoqGHr5sDW4ymyVj9f0XgHOiQ/Nb9QEkW9WOTV/9Wb48G1j5smgJhDmQQKlXDhOYtOpwHiU07wV3WOEhlNGFbZxlZipP53gEMf47B58ngJj/PA/0FDLV4MKi/cWDn4dSfT9WzTeEo6D8TEBiU7nljkpvpk6g3uoVm5TYEKPIe/tZA0uWTqx/l0j/Bx70CZEqHzn23SNYtgavMpS8uzgl4m0+p2jN1JCXni+VJPHBwzBKZC/hN+Zu+//znF+F2qMLPnXS5XB0ouETEp6CkMmGw3+qgXZD/SS44lam9Yc45KIAvu0eqo0XMIQSpQn3rKF0QhOMr+YD+/iCyXzdWVVlrJEuZWe6iK4EEpZpJ0bK8Us95uhgaIs+LVSVMxEEWSOcYbWamstWwacGFRi9ipL7Bgjhqg4tKGFZIQqY/EsLJRZKEz3OMDswc1BvbcxiirvloHi9SUBYPHpjOya4Bd+rkEtTPxYN4xnJGxLQRcqmKkbwJybNgXq42MlTt/HxzftTtLl6TalJTyqoMfCTUTr+1hJ8DdRpdI0gkkRFi+R5ndtqA2R42kgmD7FWoBuZX/Kd7IkCakHyTThikjH/1vgboi2mXKgkLuFEH91MlRn/h6YF+XatHPeX17PvU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/History-of-the-United-Netherlands-1598_4870
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy